USE [DEMO]
GO

/****** Object:  StoredProcedure [dbo].[MANAGECATEGORIES]    Script Date: 29-12-2024 12:50:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[MANAGECATEGORIES]
    @CATEGORY_ID INT = 0,      
    @CATEGORY_NAME VARCHAR(500) = NULL, 
	@DESCRIPTION VARCHAR(2000)= NULL,  
	@CRUD VARCHAR(20) 
AS
BEGIN
	IF  @CRUD = 'CATEGORIES'
	BEGIN
		SELECT CATEGORY_ID, CATEGORY_NAME
		FROM CATEGORYMASTER;
	END
    IF  @CRUD = 'CREATE'
    BEGIN
		IF(@CATEGORY_ID = 0)
		BEGIN
			INSERT INTO CATEGORYMASTER (CATEGORY_NAME, DESCRIPTION, CREATED_AT)
			VALUES(@CATEGORY_NAME, @DESCRIPTION, GETDATE())

			SELECT 'SUCCESS' AS MSG
		END
		ELSE
		BEGIN
			UPDATE CATEGORYMASTER
			SET CATEGORY_NAME = @CATEGORY_NAME,
				DESCRIPTION = @DESCRIPTION,
				UPDATED_AT = GETDATE()
			WHERE CATEGORY_ID = @CATEGORY_ID;

			SELECT 'SUCCESS' AS MSG
		END
    END
    ELSE IF  @CRUD = 'READ'
    BEGIN
		IF(@CATEGORY_ID = 0)
		BEGIN
			SELECT CATEGORY_ID, CATEGORY_NAME, DESCRIPTION
			FROM CATEGORYMASTER;
		END
		ELSE
		BEGIN
			SELECT CATEGORY_ID, CATEGORY_NAME, DESCRIPTION
			FROM CATEGORYMASTER  WHERE CATEGORY_ID = @CATEGORY_ID;
		END
    END
    ELSE IF  @CRUD = 'DELETE'
    BEGIN
        DELETE FROM CATEGORYMASTER
        WHERE CATEGORY_ID = @CATEGORY_ID;

		SELECT 'SUCCESS' AS MSG
    END
    ELSE
    BEGIN
        PRINT 'INVALID OPERATION TYPE. PLEASE USE CREATE, READ, UPDATE, OR DELETE.';
    END
END;
GO


