USE [DEMO]
GO

/****** Object:  StoredProcedure [dbo].[PRODUCTMASTER_CRUD]    Script Date: 29-12-2024 12:51:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[PRODUCTMASTER_CRUD]          
    @PRODUCTID INT = 0,         
    @CATEGORYID INT = NULL,        
    @PRODUCTNAME VARCHAR(500) = NULL, 
    @DESCRIPTION VARCHAR(2000) = NULL,
    @CRUD VARCHAR(10)
AS
BEGIN

    IF  @CRUD = 'CREATE'
    BEGIN
		IF(@PRODUCTID = 0)
		BEGIN
			INSERT INTO PRODUCTMASTER (CATEGORYID, PRODUCTNAME, DESCRIPTION, CREATED_AT)
			VALUES (@CATEGORYID, @PRODUCTNAME, @DESCRIPTION, GETDATE());

			SELECT 'SUCCESS' AS MSG
		END
		BEGIN
			UPDATE PRODUCTMASTER
			SET 
				CATEGORYID = @CATEGORYID,
				PRODUCTNAME = @PRODUCTNAME,
				DESCRIPTION = @DESCRIPTION,
				UPDATED_AT = GETDATE()
			WHERE PRODUCTID = @PRODUCTID;

			SELECT 'SUCCESS' AS MSG
		END
    END
    ELSE IF  @CRUD = 'READ'
    BEGIN
		IF(@PRODUCTID = 0)
		BEGIN
			SELECT PRODUCTID, CATEGORYID, PRODUCTNAME, P.DESCRIPTION, CATEGORY_NAME AS CATEGORYNAME,P.CREATED_AT, P.UPDATED_AT
			FROM PRODUCTMASTER P
			LEFT JOIN CATEGORYMASTER C 
			ON P.CATEGORYID = C.CATEGORY_ID;
			
		END
		ELSE
		BEGIN
			SELECT PRODUCTID, CATEGORYID, PRODUCTNAME, P.DESCRIPTION, CATEGORY_NAME AS CATEGORYNAME,P.CREATED_AT, P.UPDATED_AT
			FROM PRODUCTMASTER P
			LEFT JOIN CATEGORYMASTER C 
			ON P.CATEGORYID = C.CATEGORY_ID
			WHERE PRODUCTID = @PRODUCTID;
		END
    END
    ELSE IF  @CRUD = 'DELETE'
    BEGIN
        DELETE FROM PRODUCTMASTER
        WHERE PRODUCTID = @PRODUCTID;

		SELECT 'SUCCESS' AS MSG
    END
    ELSE
    BEGIN
        RAISERROR('INVALID ACTION. PLEASE USE CREATE, READ, UPDATE, OR DELETE.', 16, 1);
    END
END
GO


